# Generated by Django 4.1 on 2022-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaoparametro',
            name='D',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='questaoparametro',
            name='A',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='questaoparametro',
            name='B',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='questaoparametro',
            name='C',
            field=models.FloatField(),
        ),
    ]
